server:
  port: 10000

spring:
  application:
    name: magicgate-rag
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      # 这是非常关键的时间配置，负责大模型调用时间长了之后会直接抛出IOException
      request-timeout: 60s # 异步请求超时时间（毫秒）


  ai:
    chat:
      client:
        enabled: false
    dashscope:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: -----------
      workspace-id: llm-vie3wwctzt25zpie
      chat:
        enabled: true
        options:
          enable-search: true