server:
  port: 9999
spring:
  application:
    name: magic-link
  main:
    allow-bean-definition-overriding: true
  ai:
    chat:
      client:
        # 如果这里是true的话，spring可以自动注入ChatClient，单模型很方便，多模型的话不建议 如果注入了openai zhipu等其他模型需要每一个都做好装配或者关闭自动装配
        enabled: false
    dashscope:
      api-key: -----------------

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug



llm:
  providers:
    dashscope:
      api-key: -----------------
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      models:
        - qwen-plus
        - qwen-7b
        - qwen-14b-chat
    dashscope-openai:
      api-key: -----------------
      base-url: https://dashscope.aliyuncs.com
      models:
        - qwq-plus
        - qwq-plus-latest
        - qwen-turbo
