server:
  port: 9999
spring:
  ai:
    chat:
      client:
        # 禁用自动装配，使用手动装配的方式去构建一个ChatClient
        enabled: false
    dashscope:
      api-key: test
      chat:
        client:
          # 禁用自动装配，使用手动装配的方式去构建一个ChatClient
          enabled: false
    openai:
      api-key: sfafffffffffffffffffffafsaf
      audio:
        speech:
          enabled: false
      chat:
        enabled: false
      embedding:
        enabled: false
      image:
        enabled: false

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug



llm:
  providers:
    dashscope:
      api-key: sk-94ceac3079a54f68911f875500b3a3aa
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      models:
        - qwq-plus
        - qwq-plus-latest
        - qwen-plus
        - qwen-7b
        - qwen-14b-chat
    dashscope-openai:
      api-key: sk-94ceac3079a54f68911f875500b3a3aa
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      models:
        - qwen-max
